# -*- coding: utf-8 -*-

"""
/***************************************************************************
 QMarxanToolbox
                                 A QGIS plugin
 Marxan Processing tools for QGIS
                              -------------------
        begin                : 2016-09-02
        copyright            : (C) 2016 by Apropos Information Systems Inc
        email                : tsw@aproposinfosytems.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Apropos Information Systems Inc'
__date__ = '2016-09-02'
__copyright__ = '(C) 2016 by Apropos Information Systems Inc'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os, sys
from qgis.core import *

from processing.core.GeoAlgorithm import GeoAlgorithm
from processing.core.parameters import ParameterFile
from processing.tools import dataobjects

class ExportInput(GeoAlgorithm):

    OUT_DIR = 'OUT_DIR'

    def defineCharacteristics(self):
        """Define tool placement and parameters"""
        
        # The name that the user will see in the toolbox
        self.name = 'Create Input File and Folders'

        # The branch of the toolbox under which the algorithm will appear
        self.group = 'Export to Marxan'

        self.addParameter(ParameterFile(self.OUT_DIR,self.tr('Select or create directory for input.dat and input and output folders.'), \
            True, False))

    #
    # create input.dat file
    #
    def createInputFile(self,outFName):

        #
        # formatAsME - format as Marxan Exponent format like 
        #              Input File Editor
        #
        def formatAsME(inVal):
            outStr = "%.14E" % float(inVal)
            parts = outStr.split('E')
            sign = parts[1][:1]
            exponent = "%04d" % float(parts[1][1:])
            outStr = parts[0] + 'E' +  sign + exponent
            return(outStr)
            
        nl = os.linesep
        f = open(outFName, 'w')
        creditText = "Input file for Annealing program.%s%s" % (nl,nl)
        creditText += "This file generated by QMarxanTools%s" % nl
        creditText += "created by Apropos Information Systems Inc.%s%s" % (nl,nl)
        f.write(creditText)
        f.write("General Parameters%s" % nl)
        f.write("VERSION %s%s" % ('0.1',nl))
        f.write("BLM %s%s" % (formatAsME(1.0),nl))
        f.write("PROP %s%s" % (formatAsME(0.5),nl))
        f.write("RANDSEED %d%s" % (-1,nl))
        f.write("NUMREPS %d%s" % (100,nl))
        f.write("%sAnnealing Parameters%s" % (nl,nl))
        f.write("NUMITNS %d%s" % (1000000,nl))
        f.write("STARTTEMP %s%s" % (formatAsME(-1.0),nl))
        f.write("COOLFAC %s%s" % (formatAsME(-1.0),nl))
        f.write("NUMTEMP %d%s" % (10000,nl))
        f.write("%sCost Threshold%s" % (nl,nl))
        f.write("COSTTHRESH %s%s" % (formatAsME(0.0),nl))
        f.write("THRESHPEN1 %s%s" % (formatAsME(0.0),nl))
        f.write("THRESHPEN2 %s%s" % (formatAsME(0.0),nl))
        f.write("%sInput Files%s" % (nl,nl))
        f.write("INPUTDIR %s%s" % ('input',nl))
        f.write("SPECNAME %s%s" % ('spec.dat',nl))
        f.write("PUNAME %s%s" % ('pu.dat',nl))
        f.write("PUVSPRNAME %s%s" % ('puvsp.dat',nl))
        f.write("BOUNDNAME %s%s" % ('bound.dat',nl))
        f.write("MATRIXSPORDERNAME %s%s" % ('puvsp_sporder.dat',nl))
        f.write("%sSave Files%s" % (nl,nl))
        f.write("SCENNAME %s%s" % ('output',nl))
        f.write("SAVERUN %d%s" % (3,nl))
        f.write("SAVEBEST %d%s" % (3,nl))
        f.write("SAVESUMMARY %d%s" % (3,nl))
        f.write("SAVESCEN %d%s" % (3,nl))
        f.write("SAVETARGMET %d%s" % (3,nl))
        f.write("SAVESUMSOLN %d%s" % (3,nl))
        f.write("SAVELOG %d%s" % (3,nl))
        f.write("SAVESNAPSTEPS %d%s" % (0,nl))
        f.write("SAVESNAPCHANGES %d%s" % (0,nl))
        f.write("SAVESNAPFREQUENCY %d%s" % (0,nl))
        f.write("OUTPUTDIR %s%s" % ('output',nl))
        f.write("%sProgram control.%s" % (nl,nl))
        f.write("RUNMODE %d%s" % (1,nl))
        f.write("MISSLEVEL %s%s" % (formatAsME(0.95),nl))
        f.write("ITIMPTYPE %d%s" % (1,nl))
        f.write("HEURTYPE %d%s" % (-1,nl))
        f.write("CLUMPTYPE %d%s" % (0,nl))
        f.write("VERBOSITY %d%s" % (2,nl))
        f.write("SAVESOLUTIONSMATRIX %s%s" % ('3',nl))
        f.write("%s" % nl)
        f.close()

    def processAlgorithm(self, progress):
        """Here is where the processing itself takes place."""
        oFName = self.getParameterValue(self.OUT_DIR)
        if os.path.exists(oFName):
            #QgsMessageLog.logMessage(oFName)
            progress.setText('Creating Directories')
            iDir = os.path.join(oFName,'input')
            if not os.path.exists(iDir):
                os.mkdir(iDir)
            progress.setPercentage(25)
            oDir = os.path.join(oFName,'output')
            if not os.path.exists(oDir):
                os.mkdir(oDir)
            progress.setPercentage(50)
            puDir = os.path.join(oFName,'pu')
            if not os.path.exists(puDir):
                os.mkdir(puDir)
            iName = os.path.join(oFName,'input.dat')
            progress.setPercentage(75)
            progress.setText('Writing input.dat file')
            self.createInputFile(iName)
            progress.setPercentage(99)
        else:
            #QgsMessageLog.logMessage('%s not found' % oFName)
            return False
